### ISSUE TITLE
Full Map Magnet not working

### ISSUE THREAD

**Issue by Geezusotl** [AUSTIN2526/holocure-trainer#13]
I have the steam version and the versions match. The trainer also detects the game when detecting. But everytime I try to activate full map magnet, it never works.  If it was working then the pick up stat would be a much larger than 100%

**Comment by AUSTIN2526** [comment]
The issue may be that the full map magnet requires pickup range values higher than 0 to function properly.Can you test whether it operates correctly when the value is greater than 0?

**Comment by Geezusotl** [comment]
> 

in this case, is the value corresponding to the upgrade level in the shop? because that is maxed out and the value is at 10 in the json. And when starting a stage, I am at 120%

Also, the other Dynmaic Functions seem to be working. Just not Full Map Magnet

**Comment by AUSTIN2526** [comment]
I see this problem, and the issue arose because I made a typo in the offset. I have now corrected this problem.

**Comment by Geezusotl** [comment]
> I see this problem, and the issue arose because I made a typo in the offset. I have now corrected this problem.

confirmed that it works now. thank you
