### ISSUE TITLE
The trainer not working for me

### ISSUE THREAD

**Issue by Sad-Banana** [AUSTIN2526/holocure-trainer#15]
Sorry if I bother you. I downloaded and used your trainer on September 20, but when I used it again on September 22, the functions in the Dynamic Function and Upgrade Effects sections did not work even though they were working normally before. Hope you can help me fix this problem.

Thank you.

**Comment by AUSTIN2526** [comment]
This issue is the same as [#10](https://github.com/AUSTIN2526/holocure-trainer/issues/10) and will require me to update the data. However, I currently don't have the time to complete this task. I will work on the update when I have the time in the future.

**Comment by Sad-Banana** [comment]
Thanks for the response. I'm really looking forward to the update trainer.
