### ISSUE TITLE
Save Editor

### ISSUE THREAD

**Issue by Staticnoi** [AUSTIN2526/holocure-trainer#16]
How do i use it? i've tried going to the main menu and even closing the game (idk what else to do) but the option for Save Editor is always grayed out

**Comment by AUSTIN2526** [comment]
Can you tell me the current Trainer version? In the latest version, if the game is not running, you can activate the save editor. When you press the detect button and it succeeds, you can only use dynamic functions. If you have any questions, feel free to ask again. Thank you.

**Comment by Staticnoi** [comment]
ooh i see, my bad it seems i was using the wrong trainer version
