### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by sky5416841** [AUSTIN2526/holocure-trainer#18]
How do you find a fixed pointer so that you don't have to rescan and modify the pointer every time you launch the game?
小弟弟問一下 請問是怎麼找到固定指針的 而不用每次開遊戲要再重新掃描指針去修改

**Comment by AUSTIN2526** [comment]
利用指針掃描器直接搜尋HP和EX值，再通過兩者的指針偏移找到可能的關卡ID和功能偏移。雖然具體的操作每次會有些不同，但如果指針掃描器第一步掃到數據，就已經成功一半了(如果沒有搜尋到那就需要去反編譯部分查看組語、設置斷點來去找到這些資料流的變化)。
