### ISSUE TITLE
The trainer didn't work correctly

### ISSUE THREAD

**Issue by TuanAnh2901** [AUSTIN2526/holocure-trainer#2]
By somehow, the trainer didn't work correctly with unlimited hp, xp, pickup range (and maybe XP too) . If I turn on all of it, it will kill enemy and getting lag

**Comment by AUSTIN2526** [comment]
I didn't know why some people base address or offsets not same.(maybe my computer OS is windows 11)
I will try to use a different computer check offsets or  base address to fix this program in the next version.

**Comment by TuanAnh2901** [comment]
> I didn't know why some people base address or offsets not same.(maybe my computer OS is windows 11) I will try to use a different computer check offsets or base address to fix this program in the next version.

Ok thanks. I'm using Windows 10, and I just can't use it from recently patches of the trainer.

**Comment by Kai5343** [comment]
im on windows 11 as well but it does not work ,
