### ISSUE TITLE
English Translation/英文翻譯

### ISSUE THREAD

**Issue by joeyman2525** [AUSTIN2526/holocure-trainer#4]
Hello! I was just letting you know that I made an English translation of your mod, and I can update the translated version as you release more updates. As of right now, I translated the 1.0.2 version, as I was using your tool on the 0.3 release of HoloCure. I have uploaded v1.0.2 in my fork, and I am working on the latest version from your repository.

你好！ 我只是讓你知道我為你的模組做了英文翻譯，我可以在你發布更多更新時更新翻譯版本。 截至目前，我翻譯了 1.0.2 版本，因為我在 HoloCure 0.3 版本上使用了您的工具。 我已經在我的 fork 中上傳了 v1.0.2，我正在從您的存儲庫中獲取最新版本。

**Comment by joeyman2525** [comment]
I just noticed that your latest release already has an English translation! I could translate it into more languages, I just need to know what languages you would like me to translate into. 

我剛剛注意到你的最新版本已經有英文翻譯了！ 我可以把它翻譯成更多的語言，我只需要知道你想讓我翻譯成什麼語言。

**Comment by AUSTIN2526** [comment]
Thank you for helping me translate into other languages!!  

About other languages you can translate into any languages if you like it.
