### ISSUE TITLE
Automatic Stage Detection/自動階段檢測

### ISSUE THREAD

**Issue by joeyman2525** [AUSTIN2526/holocure-trainer#5]
Hello again! I would like to suggest a feature, which would be automatic stage detection, so there does not have to be three separate menus for the hack. I have determined which memory address contains the value for the stage, which is 08C33C10.
It has different values for the different menus, and you can read those values to determine which menu is being used at that moment. From what I can tell, there are only 4 values that are used:
80 = Main menu
121 = Stage 1
119 = Stage 2
42 = Stage 1(Hard)

I tested this for quite a while, and got the same values consistently for each respective map, so I am fairly confident that my data is correct. I used Cheat Engine to figure out this data, through a large amount of trial and error, and alternating between maps to narrow down which addresses only change when the map changes. There were 4 addresses that changed when the map changed, and I will include screenshots of the values and name the files after whichever stage they are associated with. 

再一次問好！ 我想推荐一個功能，即自動階段檢測，因此黑客不必有三個單獨的菜單。 我已經確定了哪個內存地址包含階段的值，即 08C33C10。
它對不同的菜單有不同的值，您可以讀取這些值以確定當時正在使用哪個菜單。 據我所知，只使用了 4 個值：
80 = Main Menu
121 = Stage 1
119 = Stage 2
42 = Stage 1(Hard)

我對此進行了相當長的測試，並為每張地圖一致地獲得了相同的值，因此我相當有信心我的數據是正確的。 我使用作弊引擎來計算這些數據，通過大量的試驗和錯誤，並在地圖之間交替，以縮小只有在地圖發生變化時才會改變的地址。 當地圖發生變化時，有 4 個地址發生了變化，我將包括值的屏幕截圖，並在與它們關聯的任何階段命名文件。

# `******Stage  1******`
![Stage1](https://user-images.githubusercontent.com/50000030/197042715-97e7ef05-29ef-4afa-a3d6-ec87716e4289.jpg)

# `******Stage 2******`
![Stage2](https://user-images.githubusercontent.com/50000030/197042720-072c2587-de05-4283-b951-200515105eac.jpg)

# `******Stage 1 (Hard)******`
![Stage1(Hard)](https://user-images.githubusercontent.com/50000030/197042724-c961e16f-20d3-40c2-8d21-e9190503aa3e.jpg)

# `******Main Menu******`
![MainMenu](https://user-images.githubusercontent.com/50000030/197042761-859612e8-4657-4195-8008-09c1e4decac6.jpg)

**Comment by AUSTIN2526** [comment]
08C33C10 is a dynamic address not a base address, but these values can help me find the base address more quickly.

Unfortunately ,I spent a long time to find base address on yesterday, but I couldn't find it. I will try again to find base address and add to my code.
