### ISSUE TITLE
HoloCure Force Close

### ISSUE THREAD

**Issue by Yuuya1212** [AUSTIN2526/holocure-trainer#8]
After I Detect the trainer my HoloCure Force Close. Please Fix This.

Thank You

**Comment by AUSTIN2526** [comment]
can you tell me which version are you using?

**Comment by Yuuya1212** [comment]
I'm using latest ver, I thinks the problem in Unlimited Coin, I turn off it and the game can play

**Comment by Yuuya1212** [comment]
And unlimited sp cannot works as well

**Comment by Yuuya1212** [comment]
Thanks for your hard work, realy apreciated

**Comment by AUSTIN2526** [comment]
unlimited sp have two options, you need to select correct one.

In new version of trainer,I fix Unlimited Coin options,you can try if it works.

**Comment by Yuuya1212** [comment]
Really thanks bro
